# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zmaj/.cyphal/public_regulated_data_types/uavcan/si/sample/magnetic_field_strength/Vector3.1.0.dsdl
#
# Generated at:  2026-09-03 11:10:39.770315 UTC
# Is deprecated: yes
# Fixed port ID: None
# Full name:     uavcan.si.sample.magnetic_field_strength.Vector3
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Vector3_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 tesla:     None | _NDArray_[_np_.float32] | list[float] = None) -> None:
        """
        uavcan.si.sample.magnetic_field_strength.Vector3.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param tesla:     saturated float32[3] tesla
        """
        _warnings_.warn('Data type uavcan.si.sample.magnetic_field_strength.Vector3.1.0 is deprecated', DeprecationWarning)

        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._tesla:     _NDArray_[_np_.float32]

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if tesla is None:
            self.tesla = _np_.zeros(3, _np_.float32)
        else:
            if isinstance(tesla, _np_.ndarray) and tesla.dtype == _np_.float32 and tesla.ndim == 1 and tesla.size == 3:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._tesla = tesla
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                tesla = _np_.array(tesla, _np_.float32).flatten()
                if not tesla.size == 3:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'tesla: invalid array length: not {tesla.size} == 3')
                self._tesla = tesla
            assert isinstance(self._tesla, _np_.ndarray)
            assert self._tesla.dtype == _np_.float32  # type: ignore
            assert self._tesla.ndim == 1
            assert len(self._tesla) == 3

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def tesla(self) -> _NDArray_[_np_.float32]:
        """
        saturated float32[3] tesla
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._tesla

    @tesla.setter
    def tesla(self, x: _NDArray_[_np_.float32] | list[float]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float32 and x.ndim == 1 and x.size == 3:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._tesla = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float32).flatten()
            if not x.size == 3:  # Length cannot be checked before casting and flattening
                raise ValueError(f'tesla: invalid array length: not {x.size} == 3')
            self._tesla = x
        assert isinstance(self._tesla, _np_.ndarray)
        assert self._tesla.dtype == _np_.float32  # type: ignore
        assert self._tesla.ndim == 1
        assert len(self._tesla) == 3

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        assert len(self.tesla) == 3, 'self.tesla: saturated float32[3]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.tesla)
        _ser_.pad_to_alignment(8)
        assert 152 <= (_ser_.current_bit_length - _base_offset_) <= 152, \
            'Bad serialization of uavcan.si.sample.magnetic_field_strength.Vector3.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Vector3_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "tesla"
        _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float32, 3)
        assert len(_f1_) == 3, 'saturated float32[3]'
        self = Vector3_1_0(
            timestamp=_f0_,
            tesla=_f1_)
        _des_.pad_to_alignment(8)
        assert 152 <= (_des_.consumed_bit_length - _base_offset_) <= 152, \
            'Bad deserialization of uavcan.si.sample.magnetic_field_strength.Vector3.1.0'
        assert isinstance(self, Vector3_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'tesla=%s' % _np_.array2string(self.tesla, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'uavcan.si.sample.magnetic_field_strength.Vector3.1.0({_o_0_})'

    _EXTENT_BYTES_ = 19

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8000000{^8~OK%*<5nfV!Q!k2oS(5FR<49y8&dQW2GftdXrolMqh!!MSk%Ktno|z`Qqj{yfhvW({5FcVl!2ljW9Y8<9Kfyo2'
        'KoBIk`JRiBORl~tRWm)iOPRbl1f;LFA5~vhbyfBJY3#3)$2#?2`EuTibQF8O=1Q_yK4d}6JwMEnJk!!}TOPS%R1um&@w>g8+b4GM'
        'Q~QZsD98PjB`|-rVA~-}JuN-Wk{os?Y%AqPhW@7HapY^Gc)DeTcaMiAQ`c-c<!^JPWtLjeDJSna`H7_?wDXz$)Rwb8Ge*gvFkIV@'
        'z}Nva`>Sj@zK+HQ^k)2s8Ri@0EJm9_F<xGDY>iB~cc+(zLS?CZ$fLV3pbZ?rib*luG7*Qtx;XB(&mY7iS2B@CZUc|`4^l1R{L!yc'
        '!?(EF>$F)vkj9T|e^|N-EJLP^pJWlRyilIL)hfbm-Wtr^#3^*mpY3g1o&;~QG-4_mR`j?C;Apdn3{|Fin5B^|$NVS@?fw6Zb~<+j'
        'CuxxcT#;;(46V|{2xf?2+nnS~YaS6T(~uLLC7dt?CKOXWlEBZ@5ShaIdZqDZP^lXSrJ0gjFufo>?p>)@p@T`lG+!iAlZbCh@CnJe'
        'T4H$~%a9p}xkpe<SSW>h`diRaq4^91iUgb}{>K7h1KT%MmJGD(e)wu-BmrVvT_KwDdQq5xUY)~1Wx55UYFonDYAUj}J_Dx!a@#B}'
        'II=VuN%=Oq3I5xRvz>-te}3iq61ary$Ow4ykO9XxXJ!alBFn#DxxUx4u$%>1VaW3G>I&&`rt}rEBV;IW3eqGsJ&)WV*I%!74($cr'
        '1>7A)cCsRlzz|p<q)1a9a;=$?aj&5O7lBBl`)t8&unpK^L{`A65m}*eRc#)oqXJYA2G&3^-<9C6)WAI^p^{o^uQ|+G40l0>OKUea'
        '$U>SKvi|NOft!$mFBRAenSx7E<mj(ANYH~MMT<G>#Tlz(41t2$;MK(MwxJ>k(%*u`TCh0A2;+6ziuqE#yfLxK2aZZO3^aGt^y2`R'
        ';<CYOfj&?;n?hg+I8l2R65(h$wU(urCZ?ZvVqU!Dq>FS_ydqwu9n2?jxk;VL4>st=`@h++VzIpRTduO_P1pAg;)dRMkY+onXUhq{'
        'CS=PO+oHgCbGUF=%=VOosoVAaWO2(!td!Gm<Pb+S%&$8c^SnbxJ_BYtC<0#257j|G=rt7=Pq84*iECo1fPxZnFbe6!Bm1~K3N?3^'
        'M?MD1myz8l=X{+ND&#N`b3bQLF3L%SSO&J7z6Di&_ZE&mvE_$d0U6zWn6N)|y|9-<n7VlpK(_jdZxt~b8I)DsZE9&3ozva7mU^#w'
        'S3UHNt*h6(FPH`nnC-sHNBbCj{<n=Lzfm_q-FP`5-7^Krk3Pj~3OURmKg~|29xT-fpoeVMA*zkS#V}$|LV<!TE}E3DGk#zPeh9fG'
        'Af>>GSpxMea)$AG1{r9AV$>GhI_0)uO{SJ~&O^B=hpsjBg9jWg#_>8%O%F|hdDFrs8gD^mMy9qrwSV{F<(WE4zR7%*Wv14pa|WIg'
        'zbse2SA-hxkNH6ix9w7UTL%pUVqu>DZOg;&Nb~FZ_Z{9(rSg!U<+daTDbc+o$bb$6`zB8^SDN34n!up<4;tZw9||Z!R(w<*yTu}`'
        '(BD}k0-W6_;uxCH^Rr^*bGtxSD;>adB5yQUI#mR4&P1lzTtQ&FC`@951?QkrI)eK;6&-bW2ywKcWA67j;z&g&-1wv$pK>_u#%B;G'
        'Dmv@dA4Z(2=n=%RiXL_Ak0H)h^thX!LmaQ@38!Zs@kB*WA|9{kDa4}{J&ky{qGu3iDtgxKf5F*3=j@z!dM-G7FCw0==u3#_D*7_w'
        '3l$}ZXDfOU@k~WuK|Ed2A0VEp=&Oh)EBZsk`HEh0ye=coRdm7eTSPoo(H}XUKSn%K(JPMck~^>Gcy|$}D|*%Oe+_Z6qRZ|a*PK6I'
        'cju|&dZ?n;-MQXy{#|wF`$-db`liF5I{cZ#w;cZ5;V&G%?eIN^_Z<p{yAB^YeCqHEhhIAU%Hh`zzj63&gEyx}oN%@k7FuDo72a!w'
        '`>h~aVYd|?wZhX@_@WiQY=y5{;p<lTrWL+*LIH0~=u6Peu)(;o0NV@ny=gOe^)8kjY@dU-?)d}W+)A+?yhPWr(KPkp1`h3g=pONT'
        '%<*;TUf>tX>2-J=m_4hY853y6%i{7QV2Pg%(iHd-e(NuDo#DS{&z`xy2>Cq?Z)T{6()27nB<_h1n|km&;SZIK6SsK|-yr)JpHcq-'
        'ZViMODkY?<os!UxMGF72Pi$K%wD|i*-(};_ilLH-Me$GQ(Bf@0_zy8B{ww}fh<6@|wGHtu6l(GPTB(-Z<|C?mz(-WqeMIf;tb#s9'
        'LgMD0Ml-4<yiyu{wmfryMvGry&4(EmxBtH$vwt+AzBC-6Q}9Z|XG^+ohrlRfg8+`$J@?i2v54tN9kNvj*(!#tj+FQ}*EsqVMxPEw'
        'W9$y!8OE@B{{vC%1%MI{000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
