# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2026-07-21 22:07:53.964460 UTC
# Namespace:     uavcan.pnp

from uavcan.pnp.NodeIDAllocationData_2_0 import NodeIDAllocationData_2_0 as NodeIDAllocationData_2_0
from uavcan.pnp.NodeIDAllocationData_1_0 import NodeIDAllocationData_1_0 as NodeIDAllocationData_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
NodeIDAllocationData_1 = NodeIDAllocationData_1_0
NodeIDAllocationData_2 = NodeIDAllocationData_2_0
