# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2026-09-22 12:54:26.295520 UTC
# Namespace:     cyphalMessages

from cyphalMessages.motorControl_1_0 import motorControl_1_0 as motorControl_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
motorControl_1 = motorControl_1_0
