# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2026-09-03 11:10:39.442274 UTC
# Namespace:     uavcan.si.unit.power

from uavcan.si.unit.power.Scalar_1_0 import Scalar_1_0 as Scalar_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
