# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zmaj/.cyphal/public_regulated_data_types/uavcan/node/port/ServiceIDList.0.1.dsdl
#
# Generated at:  2026-09-03 11:10:39.389256 UTC
# Is deprecated: yes
# Fixed port ID: None
# Full name:     uavcan.node.port.ServiceIDList
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class ServiceIDList_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    CAPACITY: int = 512

    def __init__(self,
                 mask: None | _NDArray_[_np_.bool_] | list[bool] = None) -> None:
        """
        uavcan.node.port.ServiceIDList.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param mask: bool[512] mask
        """
        _warnings_.warn('Data type uavcan.node.port.ServiceIDList.0.1 is deprecated', DeprecationWarning)

        self._mask: _NDArray_[_np_.bool_]

        if mask is None:
            self.mask = _np_.zeros(512, _np_.bool_)
        else:
            if isinstance(mask, _np_.ndarray) and mask.dtype == _np_.bool_ and mask.ndim == 1 and mask.size == 512:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._mask = mask
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                mask = _np_.array(mask, _np_.bool_).flatten()
                if not mask.size == 512:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'mask: invalid array length: not {mask.size} == 512')
                self._mask = mask
            assert isinstance(self._mask, _np_.ndarray)
            assert self._mask.dtype == _np_.bool_  # type: ignore
            assert self._mask.ndim == 1
            assert len(self._mask) == 512

    @property
    def mask(self) -> _NDArray_[_np_.bool_]:
        """
        bool[512] mask
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._mask

    @mask.setter
    def mask(self, x: _NDArray_[_np_.bool_] | list[bool]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.bool_ and x.ndim == 1 and x.size == 512:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._mask = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.bool_).flatten()
            if not x.size == 512:  # Length cannot be checked before casting and flattening
                raise ValueError(f'mask: invalid array length: not {x.size} == 512')
            self._mask = x
        assert isinstance(self._mask, _np_.ndarray)
        assert self._mask.dtype == _np_.bool_  # type: ignore
        assert self._mask.ndim == 1
        assert len(self._mask) == 512

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        assert len(self.mask) == 512, 'self.mask: bool[512]'
        _ser_.add_aligned_array_of_bits(self.mask)
        _ser_.pad_to_alignment(8)
        assert 512 <= (_ser_.current_bit_length - _base_offset_) <= 512, \
            'Bad serialization of uavcan.node.port.ServiceIDList.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> ServiceIDList_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "mask"
        _f0_ = _des_.fetch_aligned_array_of_bits(512)
        assert len(_f0_) == 512, 'bool[512]'
        self = ServiceIDList_0_1(
            mask=_f0_)
        _des_.pad_to_alignment(8)
        assert 512 <= (_des_.consumed_bit_length - _base_offset_) <= 512, \
            'Bad deserialization of uavcan.node.port.ServiceIDList.0.1'
        assert isinstance(self, ServiceIDList_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'mask=%s' % _np_.array2string(self.mask, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'uavcan.node.port.ServiceIDList.0.1({_o_0_})'

    _EXTENT_BYTES_ = 128

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8000000{^8}>u(iB6mQFId;5Zx3k7-DRbB<@ULJz@#M0WN8K_OEL_e6x+}&wsWbf`~X7}1lVgesDMJHh+!yjPO1QYdx@elNz'
        'y;HassfpU$^tXG?nKS2o_I~Bb{n5Vi&&;IlP=}FEHCK{F@*ZnM+^0d(OcO0LZq39Zk7N@b!}WH`?PGiPf&I$PnjtFVm@6y#%*5?X'
        '<w2G!-YYUlW7Y%}ujZ^3u-K22ko#$(GXFMLEgA6T#hX%R)>LVWD=m{4wGH2K&yOwXBmLjl2iA;HmSsvd@{DWyIjG*n?q^cg3@%9?'
        'h0l!{r6J20&Co(~beH2wv9>h_mgE)>Z}NCE6Z1&wb!&q1h&OqhIc2-pk}3?FY=OksjU<UUi+lBq(T2=uR9<6AKUf$rozW&l$%+{>'
        'y}F|SkNFG0yM-(a%hz@d%%nPFamZBIt>|IiFe9KTWr57v_Ez73snABGtvS78=W}T=IeYQln(-Sl>v(?~UY)&W4^2{Qyxo-OcC(R0'
        'GO(t0i#HR9LIz3vIOU3EiR!MKKuAc8xNP>X@swxs<#Ge`E*dYcf#ANCJc^iVzbFODS}e-BePm}zf1w-TdxbV-?A&g$t@3FYgPKPS'
        '6_b7x?kmWE!##)t1*y3ALH9o7aJZwKR2_c=v09K(#~(u+D#*B_PaqB!WUqVQ=j0~c`6>6l-|=gR`wMaaal9Z09evvAJ>>APqrc+h'
        'j<|D25swt)nByNutQF){ch3ysWI;T4|7(a-1$o`^PasYg<fJ=)3UQ_&r=9*Y&YxLCuOMd;4;18_lYay8OhL{g9xKS4)9*XG>xkzH'
        'a>1Ry=<d7Z{J8AwcoXq_L9QU4D9Bak*IQ2CHFw|Jh}R184&sG^yo)$nkoTPa_Yn^l<OApTb$9N=j{iCI8Q)4-T+SGvL4g!`18YZ&'
        'no5)DyB10(OrVlKT^HPwamcqk#Z$#KG`;pRB!=)PHzZeHS%JQ{u5#|p&3R6&o@*ZZ-V%#+NoI`>H7@BEE~}a9LK0&OKkKnsaTprE'
        '_6gXw8S`*C&iE!*JyS!RB$MKlI4jO=mj+iC=2zzzme)VC;ycr4#SL?Or$fO@um#=h8AjE$vNKt<qZ7`IY$z5W6~;t$$vp!fVuKTS'
        '&0=`CsdbHE+GuyiI~w(^m=;gOqa0>hh=B?i><hbX_R<X;r4)xgm7!fRQ&cCp3OFz#PE!UG%M2q#vSH20Dr}vtRir+)=1yHCO<up('
        'WM9<%pq&a9)ziEILxw883H=P0JfG^i-dQtsTr+jNvEH+0{0sg?A0uPS=~<(KX)r+HAlDs1`w)Wo$GjJTxR-2rj@*@P?T@YtsXh2H'
        '4?@v`f$s$_jdNPw;~oq~EF$kqnF&vW10Gg{YVpw1FqE;NJQ(!6tRuzZP2P3Y-0~vomT{ms$b_RH%)E^pmn-OLNlYio<Ka{#SrR0X'
        'Z_Q+xi_YGTu}aG=In;>=)HB8e0HXpcy?6a`bEr%N%@V4TBr8>wrdsjTT=`E)C}S+ni+ZQRE{Q9ye9LjZ%EC~_n|~Ynz`Y6|18IkC'
        'Nfk<b5tqP6_-_dmZLjRKsu&aFVp2?jpHO^{xcH&F5XFz%;-?kyvv?|gDNXqmQY(HFzyFJ{h(G_I`>=NSRtCv{HmaCu=#0*Xl%j&O'
        '5TN{g5Z^y*Y!4dy4CycJE!%sS_#K3~fgKjVbj9NK#|;aGjYS}?yC(09N8RXAb!ZI>@SpbZ5WQROQF0#+bnB{?`&KNHK1@#q)3dW9'
        'b(trwk?R51dkGg0`+ouY;C$<g3IG5'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
