# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2026-07-21 22:07:53.948212 UTC
# Namespace:     uavcan.si.sample.torque

from uavcan.si.sample.torque.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.sample.torque.Vector3_1_0 import Vector3_1_0 as Vector3_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
Vector3_1 = Vector3_1_0
