# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zmaj/.cyphal/public_regulated_data_types/uavcan/node/435.ExecuteCommand.1.3.dsdl
#
# Generated at:  2026-07-21 22:07:53.015723 UTC
# Is deprecated: no
# Fixed port ID: 435
# Full name:     uavcan.node.ExecuteCommand
# Version:       1.3
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class ExecuteCommand_1_3:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        COMMAND_RESTART:                 int = 65535
        COMMAND_POWER_OFF:               int = 65534
        COMMAND_BEGIN_SOFTWARE_UPDATE:   int = 65533
        COMMAND_FACTORY_RESET:           int = 65532
        COMMAND_EMERGENCY_STOP:          int = 65531
        COMMAND_STORE_PERSISTENT_STATES: int = 65530
        COMMAND_IDENTIFY:                int = 65529

        def __init__(self,
                     command:   None | int | _np_.uint16 = None,
                     parameter: None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None) -> None:
            """
            uavcan.node.ExecuteCommand.Request.1.3
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param command:   saturated uint16 command
            :param parameter: saturated uint8[<=255] parameter
            """
            self._command:   int
            self._parameter: _NDArray_[_np_.uint8]

            self.command = command if command is not None else 0  # type: ignore

            if parameter is None:
                self.parameter = _np_.array([], _np_.uint8)
            else:
                parameter = parameter.encode() if isinstance(parameter, str) else parameter  # Implicit string encoding
                if isinstance(parameter, (bytes, bytearray)) and len(parameter) <= 255:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._parameter = _np_.frombuffer(parameter, _np_.uint8)  # type: ignore
                elif isinstance(parameter, _np_.ndarray) and parameter.dtype == _np_.uint8 and parameter.ndim == 1 and parameter.size <= 255:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._parameter = parameter
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    parameter = _np_.array(parameter, _np_.uint8).flatten()
                    if not parameter.size <= 255:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'parameter: invalid array length: not {parameter.size} <= 255')
                    self._parameter = parameter
                assert isinstance(self._parameter, _np_.ndarray)
                assert self._parameter.dtype == _np_.uint8  # type: ignore
                assert self._parameter.ndim == 1
                assert len(self._parameter) <= 255

        @property
        def command(self) -> int:
            """
            saturated uint16 command
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._command

        @command.setter
        def command(self, x: int | _np_.uint16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._command = x
            else:
                raise ValueError(f'command: value {x} is not in [0, 65535]')

        @property
        def parameter(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[<=255] parameter
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .parameter.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._parameter

        @parameter.setter
        def parameter(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 255:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._parameter = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 255:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._parameter = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 255:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'parameter: invalid array length: not {x.size} <= 255')
                self._parameter = x
            assert isinstance(self._parameter, _np_.ndarray)
            assert self._parameter.dtype == _np_.uint8  # type: ignore
            assert self._parameter.ndim == 1
            assert len(self._parameter) <= 255

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u16(max(min(self.command, 65535), 0))
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.parameter) <= 255, 'self.parameter: saturated uint8[<=255]'
            _ser_.add_aligned_u8(len(self.parameter))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.parameter)
            _ser_.pad_to_alignment(8)
            assert 24 <= (_ser_.current_bit_length - _base_offset_) <= 2064, \
                'Bad serialization of uavcan.node.ExecuteCommand.Request.1.3'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> ExecuteCommand_1_3.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "command"
            _f0_ = _des_.fetch_aligned_u16()
            # Temporary _f1_ holds the value of "parameter"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u8()
            assert _len0_ >= 0
            if _len0_ > 255:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 255')
            _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
            assert len(_f1_) <= 255, 'saturated uint8[<=255]'
            self = ExecuteCommand_1_3.Request(
                command=_f0_,
                parameter=_f1_)
            _des_.pad_to_alignment(8)
            assert 24 <= (_des_.consumed_bit_length - _base_offset_) <= 2064, \
                'Bad deserialization of uavcan.node.ExecuteCommand.Request.1.3'
            assert isinstance(self, ExecuteCommand_1_3.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'command=%s' % self.command,
                'parameter=%s' % repr(bytes(self.parameter))[1:],
            ])
            return f'uavcan.node.ExecuteCommand.Request.1.3({_o_0_})'

        _FIXED_PORT_ID_ = 435
        _EXTENT_BYTES_ = 300

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8x$R$S0{@j++m9qw9iEYeovj6SaAm;|<hUx#Br|Ok72_tD*_j@g40B1(EGq&jPFJ1obJ)63b*g826A}m!At@tD86J!eKKR6g'
            '@xiExcTChL6JPuf{1?27-|w8N>dW-X?k1b*u0EIF<@<fV@0@z&)OQ9C&Y6G3L&?z3{GjD#B2_$4*LgP(E!T^~B+ir;WpUSr2vmrV'
            '{^2kY<=f@*tL4k(QgMf?qDZ8roGb1+&}r`JJQb5eZg(RdVu_16A9y@!MX@hh?PKBPTCB%m$Roei5ijK;(`B*X4n&%%IHDC#KV5x('
            'yWF1NzU}q$)v`G2a;;O<#pJAf9?Rdr_GVOB+`g$q;ExP)T%T+1YO?Z1)033ERRfGTe<jLPKN9{{q(xt(lir<myGpx(i27QV+lyG-'
            '<C%6tI9bY%78myGg=ku99l!0+Pw;5&Yh|Y_KH_E?5#XsmzR(+aS31RM&xWTgPPu;UmBrr<s<A9d#i}oQ3TCltRK|EJ7}rco!E~Ik'
            'xMx15Jn9R!RFCe8AU;}dIZunokJF4HCCvVY`7j~n>2QS&%&)6iB0SYo-e?aMnMJ#?)^W%Zp6aQ6;7+Pl)MvdE1FnlSZZ?~-Tqb!C'
            'uqf6n&jeGxh%^Qu?TmNhfnbk*_OUNK)+!N>du_nw{lx<}$atFaVOiYwG{;jsdCG)xjh;@X>@HUXBE(J>0`h@s<&SMI$cN-7<R=mR'
            ';tcYba8K!Bx&40e;VLn1kDxSj-p9A+DWP`uDYqMBW$|!r=_s`@T2Fs3i#snXZS6h4*UHl3HaAYng57A5Y#4UqKmix$cSIN?4jRR>'
            'mxz?>I32H1Pbw6E{Bm*cdK`INi)iLha+*e_BBIj5_;b5?5C9M-M&98Lc#w<oo8{8>!dqEau2sR<z^wZ^1ci=BgjP2)>6#nzV}uqH'
            'o-z;RUcHuyU#KFK2z|h?oxh(hPE$?g0jK%f^E7tut?dQ-H%Hlt<Ag_sEq3#+fJM(DEzj-DEy(9*&5#_!XfM>+8Ne76rHRKLF8;j6'
            'GH?eF+&pGko+N=n_2}4Oy~1yc9pXzbPD7L(zN0!Y8nvlSe3{DXkqz`)4o#_RepCp4+*E;<m}h{-mOwl)s#@vg6(){7k(kobX4e3P'
            'jBj6Z7+YoQdpkR8yBqH1_7hvX?!n&X;nlTH+r6^Cv3A&|`Z-@LAo;X$127cR7>E}e@FOJW>h(J9gTuAXAqD1@j_Ag*<rhQZ&Tg#9'
            'TsWV_;ViF0K4fuf{*ZSmXkHOX;gjJBqLVoF5n&1}zb2UI^@OJ{G12O`R#=aFz|D|`1M$E}@nBsI$Tyx+!Y9~zp<_bNgW5^VInztA'
            '4xXYU7dETU_<iU7_qXR?N6{J_$PbFiJ#|d>_pY`(?%w7mMdhmpGS^7oQPc$H66@tDzNCzM9&BVssv^0rVCbls0zI)DR2P^zNqmH{'
            'NIIIQp=j=1WAF>M%a<xA<Y4E&w`A>u{~r<Z;jetpnVY*T`W2&RaZevn2gwt(M;MjH#`ZiT#8th!r@*uw!42|9=thFCiOhhvY6cgZ'
            '+PPRk+4LQY{!v|daiqD5G8+c2WnEyAI2u``LXOTtd(+Q|Aw@fgxlgegTI)p$;b41?DNs~vq#bL#9<MkWsXQ^mqrI+K#RA$CVQh$t'
            'DmgpiiM29~1GrkbX}6)$cScsU9Op`cIjJ!9ice<rC|oP!CNJ4|i)D)vLA*-wKa#>gNNGYwgBlZnDre3Oa@Jy7J?jN#`U1TU%oNs3'
            'tc)|5-4r2B#fzvrK@X6HII1)0h%}8UQNGAntsyGNp#I=zMy_}hewuNH`q`2#<jZRtE{No?%~Y?c6T^>rigu%ep%X`|ey)dxM>!bR'
            'hZwMgn&wRym4-6FW&^AagG@}p`d|>4l}8!x!9Q9di{S*62O<H1GlgkP<3Wm~4>1RGkND6=rOE|lNt^?-&>*ShyLu)qU2~U-R1H?b'
            '(TbBt0gW18%IYh45t78Ju!S9LKY-N+*UC=HP!|=@tMt`&b_F4M1pE~TNjQ?qlh}czQ#BezX4{laj?WIRtgp8Z4vghgZYs)!*(-*F'
            'Q@C*qZUixON-1Kofgq;&CYu@QPA|y)x~fvE+eN+7WE2gy&<w$9$mp0MjzI_4))4D2<YU&uW_6@d*eV*t*KWFiu~Q<jrXLK)xRri('
            'D7w}9gp(db&5$i6fuP8xqF41FNzCHqBn@rVqqEyY(1C%G>NAf*(~=|G_h}q(f*wHF%rj6GVCP(wHj87#3M*_DZG8NhkVBs{3(*0B'
            'Em;qUJ}=UPi&S~z$EYU-fY^oC%MKja+1qGO6Mc*A-;|p(SDooCoZB*B0~F$Zq^=X*C`e(PK?n>1hp=jSk`D}HHC0TTs}#t>T0x!3'
            'jD~<|X@^;@$XTk&%7_dz3QW)plIW{M&k2PVW`XIfyr&5BtS&8EC6Qf3s=i$11FizzRRKhPZ8xQEM|r>?N(EFO&{4#AM_Y~H4vVYW'
            'u^#nQ8X9Yi)Dd<>MyD`gPPz>{(%_2onn{i!EW;^esR+BmH@yvN%TznM1P?R-(w9|9!re6Ho)q@f*R%)tdnAHj87&~Pc9Y*L&QSx$'
            'S*uer^C&_9EhY{4P)=Y!3>+wKpCSj;h-X8k!f#hNvtUSu1u+uDv+DdfwYk|_42bf3#5^{-tEmX6RK_^pA%B~$(eQVRZ33&}m{ayw'
            '>Mk?I`#mI_7K{98Bj6C}Gx|0G!4;>WWfPQ{zKwdQjaaKH5FTXli7HXVh2bQ`sOohSeNJZ$&z7bY*Q6Buafd1(j;f5xKj9Otr->b;'
            '7B>X8l;vm_RR$=1t6LkjlBv{49hwHuW7>=K*)nkL+yF-QG^8n2UZs$z*%9$t$<3ga7?_g!b+fMrk<|!?`jljeW=jA5=a%&Ey|w<`'
            'Tw6cf>pVjznYKB{yw|ZUsgA-UMnv>fKd;1|(ccwQ)+Z218lDHb&Q!*hsM6~LO(hAy9viu+r{<9-Qj)izms-t@oqV!-HfX9ZB9SW3'
            '5+$}2StCILfIB1B^Ty6i)1mqIErsSn9h&w|yYobQcl{Y?v%P(a&9~Q0vly3HA><?V>Hr#vSe2Y0okfhL>tjr17h!+1I{S>ovpxQq'
            '`p5H=XP{9~YE_EhSl+~fQ?CB&mRx<Pb`=hyVE5adgRO(Z_U@roqX%>jTK~}8+{9@H2NH9YIVzNj%~MOEHGfZ{W^}4CS0h#{TDDH;'
            '9us{7b4<`Or#|LD^bTT_Db*KkfMRR0T_d*5ZQe-F!7{4E6H76k>zF#Thrviu+y!4Zw*;mY0X)w5`Gd3-eN+a@v<WlJU{%fx%R&)S'
            '4NUArJQ4|_Ri1)<pM;$tkQLKkoyd4Vc@Io2nHvq%gFTv~->$Gp`D#Xt-M7@ugwB*WnmzFW_2C$)C?-x>6L$+D%JOtfej8Vba44yM'
            '(|DSE`?1KPNAyTcjGT9x6nLV_3JsXX=|67?r;9aCw>ALIt<7f$n2*oj6fhGx%&MGJ7pOy$kRs?cdIvFDU9~4M<h~d1Oq$Gtk^533'
            'Opa*KfEjsxwdL2~uKPm7>4Lu|@A|&BYF1;%t0r#dm-?!jj{jrs(9y`I7>e9zO_}3|iaF?V+TdQBre*Koo3>Te*qHmwf(|B=8{p|Y'
            'na;^S#&RNx^JA|P-0sl6rl8z>N?wpcF3C_T`LZ0!ugllux8yhEcjY_s2lD&!hw|OLIP3a?PD9jU%QuU=-JUuYzDo+gRerf!+~XpU'
            'U~QM0r%TPVEKbv(Ky}OF%zm7y<9&MicDYo{f4VGA$(Y`goVp(J7csQu4HL<OvUniLyAT9!D*CzU=%e=+Sy|j+<rwCX{}}zbM?XLP'
            'dgU{%M_Y7jR%&|XaNd<XgF(b$Zl%G?H$eVB+M2*uB?)SnRfNpUZ2+1A!GA*B0y!q_bV!_fH_>v|h-6OO4-&`4iDiXLOtl06N;<5c'
            'g9=dVmimAZx`4H66!^8T43O+rSuC2g*;iE&9I`Kkrh{_#WIzzz`i+w)?lZY@b?l~)GG@6f0mYQ^=S%Vz@|W^g^4Ib=^0yQ_`9*oj'
            '!s+pe8}D=b+^0kFiJNZxIvTfWr*6^R`snFjnor{w;frr&-C_ZznRUzU`J8UF7v*#K|2ziK^|icg@44@n&+RNOj2{1Wdm*3k+}?J}'
            'v+_>4DDNR7E&${T0DleOeh0vQSI8gVYyrrhyeWUWD}Oc>CHbEGor%=%fhhS0`NvyKhy2rwuotIYaZEk0+<D<laRHTQUq+^`6r?;)'
            'ypUnw*2gTj&dk_&CdQ-ACSPS7R-dl!tjy1RQ6Zn*MT}oKLou#jEo3IxCNuQoD>HtisjdG3ldnMQfgJz<'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        STATUS_SUCCESS:        int = 0
        STATUS_FAILURE:        int = 1
        STATUS_NOT_AUTHORIZED: int = 2
        STATUS_BAD_COMMAND:    int = 3
        STATUS_BAD_PARAMETER:  int = 4
        STATUS_BAD_STATE:      int = 5
        STATUS_INTERNAL_ERROR: int = 6

        def __init__(self,
                     status: None | int | _np_.uint8 = None,
                     output: None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None) -> None:
            """
            uavcan.node.ExecuteCommand.Response.1.3
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param status: saturated uint8 status
            :param output: saturated uint8[<=46] output
            """
            self._status: int
            self._output: _NDArray_[_np_.uint8]

            self.status = status if status is not None else 0  # type: ignore

            if output is None:
                self.output = _np_.array([], _np_.uint8)
            else:
                output = output.encode() if isinstance(output, str) else output  # Implicit string encoding
                if isinstance(output, (bytes, bytearray)) and len(output) <= 46:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._output = _np_.frombuffer(output, _np_.uint8)  # type: ignore
                elif isinstance(output, _np_.ndarray) and output.dtype == _np_.uint8 and output.ndim == 1 and output.size <= 46:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._output = output
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    output = _np_.array(output, _np_.uint8).flatten()
                    if not output.size <= 46:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'output: invalid array length: not {output.size} <= 46')
                    self._output = output
                assert isinstance(self._output, _np_.ndarray)
                assert self._output.dtype == _np_.uint8  # type: ignore
                assert self._output.ndim == 1
                assert len(self._output) <= 46

        @property
        def status(self) -> int:
            """
            saturated uint8 status
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._status

        @status.setter
        def status(self, x: int | _np_.uint8) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 255:
                self._status = x
            else:
                raise ValueError(f'status: value {x} is not in [0, 255]')

        @property
        def output(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[<=46] output
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .output.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._output

        @output.setter
        def output(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 46:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._output = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 46:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._output = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 46:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'output: invalid array length: not {x.size} <= 46')
                self._output = x
            assert isinstance(self._output, _np_.ndarray)
            assert self._output.dtype == _np_.uint8  # type: ignore
            assert self._output.ndim == 1
            assert len(self._output) <= 46

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u8(max(min(self.status, 255), 0))
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.output) <= 46, 'self.output: saturated uint8[<=46]'
            _ser_.add_aligned_u8(len(self.output))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.output)
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 384, \
                'Bad serialization of uavcan.node.ExecuteCommand.Response.1.3'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> ExecuteCommand_1_3.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f2_ holds the value of "status"
            _f2_ = _des_.fetch_aligned_u8()
            # Temporary _f3_ holds the value of "output"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len1_ = _des_.fetch_aligned_u8()
            assert _len1_ >= 0
            if _len1_ > 46:
                raise _des_.FormatError(f'Variable array length prefix {_len1_} > 46')
            _f3_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len1_)
            assert len(_f3_) <= 46, 'saturated uint8[<=46]'
            self = ExecuteCommand_1_3.Response(
                status=_f2_,
                output=_f3_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 384, \
                'Bad deserialization of uavcan.node.ExecuteCommand.Response.1.3'
            assert isinstance(self, ExecuteCommand_1_3.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'status=%s' % self.status,
                'output=%s' % repr(bytes(self.output))[1:],
            ])
            return f'uavcan.node.ExecuteCommand.Response.1.3({_o_0_})'

        _FIXED_PORT_ID_ = 435
        _EXTENT_BYTES_ = 48

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8x$R$S0{@*?TW=)A751=R@36}*3ubq@2xzp)Y9mFHpe0Hqq@Y<}z?${g8jm3gL9LqZW1q_Qjjn312MGy;ARu)VqHV+jFUbQ>'
            'Jme`#khmt1l04;+e~{mi?^Mrt>|re7ShA<5`qZiKeD$4+-<bd4=J`4IQ$CpuLlZ_V-%zeqq+e5mh+2M-##w5#rK&u?Op%W981{!5'
            'Rd=f&yji_oT`w1Wog|c3JXfCIvUw5MBB!G!r~O35aB;Ozdx1(?Ng7gXWuJn=(o!17DhXRXGFh4!ST+4U%8gDFae3y&(evG^)99Rf'
            'r+Tw0&-u#QTo16@RIkAQG2joZs`B)zrYM{sI_rnZD&Gps<F;qHgsb;pvACTWy_-<DmRQ=Q{AhUR{DHQ9M9Hq@s?&t?KpE@Dh_d2G'
            '%FCN$N3yN8gm>%m3K7k{UG=K+A>UX~pz`prqj!q|pDh>g$`+<7=lw7Zs`Al3lb4ezBI~6)o^{_|Ey&nbg$<W#Nc?d5*fE^sxf)jG'
            'l@}FOv2x2D)|S<yL7n$0qL>m}lf;jWJU`KC@{@d(zXyEfy@)hZfwse{(<&bvLHBor?3w$X>NF(ediT6Ph!EMeG15u!0BxtgSLJ;-'
            'wXN}P;p+%#dCE_-s`QR?VutY`jWnoRT&Fk%4;FIT$S7Af%@4~sU=4}zbLFL_GzpZYWTvSEEtWYYB0kvP-z}m@<->1TF8F&YDyaHh'
            'b-mMk-we1tB4Zi5uJly0OFhcS>f<2Y_G7gVYO&##TjY(gFUMc36NpG2V78t$$}^(6B2u!y(-7Oa_dCt{vw$#ZKU0azr*1JIAbJ_s'
            '@~idz2EQ_E2P>G#S)#<WuvuX%zV?f2jk&pYGW6;dh)`KCNQ)@+2ILinc8aK8WM!O0MI{3rK_{L~VVdmG&<n{b9Z~4%WGBsIM|SJ%'
            'HuP$+A@K|)A#7cFFdqIu=>Z{)Jd;tNcXZ%M693SP^lgH-JssecOBXNAy_l3iB@zi6Z=izPILA{k$VtVKMlyTwjLOwID>*ez!O4k+'
            'T}Tlr9BEk_&*|EuI71vo5|J?;2!*(`jfP`X@S7s${Ejx{a&ob3LQvxWK(t8EnF$4&FKqSO{p~G(YkO&FWorv`m)@3DxfQ=T&T~~W'
            '^h^;10063^A!JcLK2882LVb`sK2pM(Jx8#L#u%{Y-kn?pvWhHhu8y8vUFtO6L7KXo=kJPmwY_$0ySE~UpIvg)C8-r&b1TS22O$}q'
            'OCW^>%`_5?m<^<kselO?xWTWE5b_?1{t2L58bRr9^!@gB|Amd-+Amj@1<}=IO5|$7f<%Im=mGUp6_(R{R1~I8zUL$-KR7!1W_#IR'
            '+E`z2cipi!`jY}p2io$WB?<a=lHN&#8%I=;WvN{A6pT|Rf$`8G7@O^0dwr$9(i0%hIgR6pNLa{Jj)rV0mqZ)UkGu`NJKD0lDTC@C'
            '9D+OrYW^gkE*=6Uk4_@b3!tFLQAV9eERFk_Ob1?=Qq2*nA|yQ0Jua!X0)exEo&JC1vepGl-S#birPteVbgc@y)Kz3Tb5sggDuGKp'
            '3PBA<3zQ{P0;F6`)(#39YL1r%F0yHG3lnfuE*_d<{K2pukp$%T`7#q<=a@CW&O`nUzs0}j-||QNA%Dz&<UjEz1!j(rkmu5-!s@;9'
            '0($N~g}x}r*J0HyAMj0D<N@JDM1H0)QIu!oBhmx(uuV*L`<t?Q7oDc@BMcav%8WMuTC9Ez(^fFd7}WxUL@_{#^K;roW5IEg(FtW^'
            'p&se5Pp%Et&)oRQ^l0~V>qbjzQ)Ok^S@h8r07x!gh7&2<)w|$)t|~7&7V4=pk;3i9yXiA79Q7}?Z9F_udBw%*+tkm~)H;6#BMK&w'
            '&#v?5`~`o>U-8%cH^IU`<7eyJ`T3F7eE+5jL!In?t0m*@#BR0Tx+X)wWc8bar|FK3!8WV?Vw5dLtrx%Oysppk&AK69L_>a~F<Jg^'
            'r&-KcuiG-8<NNp`KOi73Lo^zKc?)9s5JLHc_|M-}Q2dwo_^)05bc!YZJO9Hm^-tUo|BL^9()-~5%-|hk3hiUQvK0a<FGI@pe-^pV'
            'q(Xd5kB%O)_NR5$&b+e2S8<qj@95CgA3eR)`SHw&ieK&?a6F!Yj3e9KjJ*8AjF+;t^*<dxTRTk+000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.node.ExecuteCommand.1.3()'


    _FIXED_PORT_ID_ = 435
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8x$R$S0{_ig*>5CQ)wjuH##4ceLsm@`xSF8g0lQfO1QGbavD*`?<AruRVGyWtyXv-Yd1|AUwmXPV3DSp>PbCqNf+vu8;(;d+'
        'JRv}02eAkt9{CUW1K0__bMLL{>Ynz@m_;H|%H7p>Im_>y^E>y>^JhN)^wOOAuXtlTa#PoD*{Mi8?t9PizAsv~69sXUdYLGTJN85}'
        '^c>L}#iD$ry!=A>sdA}!ot=nJ<RZ=NjNZ$+;&to7_X13DCr6&Oy)YDs8nTxqxs&C|)MB^WArG+CrJN5P9=5{B6|MHMaPmy7MM1zr'
        'x7F3#mBoTR6iMnuA+31sY4iD&vNPYg?K9;I5ZLBfmUw+kPRoyD`4e=kN0r6x8=mmpu|SsX@{DWMPMRJkq^&o^h`aa0)H?`;yBTKU'
        'KqQme-C_5=%=Sfikjb*Mh{YWay9H3Ply4~R+pQL&X{|N<wnaZdqq+YpyJc~Yoo28APu%80FXnxDp*ZJg^OVII+l`#E_`{wV%i=_='
        'xMJWzEM`Wfj3<KejAc@=EQ(n)P#+T>9tgHnjqVFSI=bAlo))1SB`JeTnEnm(Awt5F(J~vVUsuvtINrc>#(Q|7TC^W!Sro9CC)w0K'
        'P$$W}@PG{x40ui?QN7uW<x<IgpM_Dz@>DR-6=8+}a69AuXeijD?|ke%kF`pe<DxdWe5iQv1dk^PAC<-ZPjkG*o2Qg1SLy9Ex`i(S'
        '>}1f*%*qdU7UY}clDrJ-7w6%}m^)rJDm$+huQ!gd2Lz>=^B(EUlSB3FGj`uk%i@tr(y?nHbT<9HEMEJBmuY$T@YP6K+-65{S+J89'
        'Nk>6H@;%_<?ky2SutSDm*@;EMvnXlCs3ScDfLt%`U5i48XCj<Al$55Ci3lmQF#f`J?)w15btBK(L+<CI{A{_@S$H|^%MD|UP0YH#'
        'OHk;FSY+NwB3-isehkxM!iUvM*{jx4_6xiaAwnN8Z0nEbigOfGxzA~SXP(B+z1&&Qe{+PLIF5O!vc-1Z7m(;#xP@=cEy(_?8FGMO'
        'v=`#+JYb9zl~EphYw?>^mLhim!S!pF=5g$Mh@LD`SU31>u^zq*q9j1r;X9%OqY;~#vM=+}YGe)lmPJ#lm>&m%8`V*eNz79~V@pUp'
        '5u)15E-y22?1)%}R;G6K5y<%VK8vvxwzjjiwYt4-KheIjxoz+5Z1kR4?Y8ax-SyR8o8sqzVgb&ljcb4*m>M8nticbHT&ULTw)c9g'
        '-5wd{`L5_kk<KqFiCf!IM&d&GGzw;E74Q*@67`3)qpIRjlENpICn%jni3<ypVfi(|#9$zt>~SVq2d!l`;0|yzqTxV1Fj72JMFaee'
        'x8(4NY`xG`rssa8B<7qSBv=P;5t0iV<}-fZdiB-L{AUof3J1Z>Y;sp+lii(X+Fg5RV}q>n(LI@GaNki_8|HB~$P;`?7<U}V$c{Xd'
        '<obf4@}?fr6U&k6d^IPIjxZKZNAXlCnmgAR^n&biXq1qj-1_^eq<!edh>&mn$d|0SxhKSd$>?b`$d0Ij<T1)4gi0bMd!7>FOzj?c'
        '$h2L-74paEhJ&w(RDstNgG+VnTryBrbw{Ir99K>hX50%?Z3dpnD!@W<G?vH<I4TS6O+UkiWNkm<F4=0Nr3a0{daCBA07bNhnWcr#'
        'nh}?3!ZSmooxWN{16l=Pq!JfJa(cvLEoBn<P}QiZx1rFt#!|E_Yd^-EM5uVhCpCI(uH~l4OWNMzvPOxZyh`>zl0req%Lo}YYLo$t'
        '&#V)C)?%9jtp#Sf0<{jADX5lMZe}pODNLG(L&Tk+7w|$9R-Uv(l0@VvSEQ`s5C$@cKj@i~D$azSYMe^_Y)J?56RYbs5=pPkyg?l&'
        'DnI54%1!2vtSDS@^K7K@C`ZP1K?Za}P4e1|UIu1>&4ySV0x6p!>m!3etUOHl0Q%7iX#^#}JYWeBoGDCW8ut@8eS|rfd&EcDD#jO}'
        'B~cE{f`cSF-&Hed=_+?AOI2Vc94%XU=+mg?Qkq{ui-0JW!4`JV^#D>UTzh&_inuU9H}0$C><dEj82HN;oNy#PM`8z}PG&TMOqVI`'
        '9GC6wudTKB_LSrlZeExRwO0fMr*LB_+z86h3Au<x3WAvCDsQI5I~_lFtEe(<f~Z!Sw4%ZmiXpNZJlYV%Qt05B7DVd{`j`%|S!HPi'
        'wigbgYquQ0*eMoR)AdJ<+)6)NWL>j9;bZ_(Gh$1zFUWF<7?}DaDYG~^Q9~W|sO;Ji)G#n&ed<-9N^+>{K8*uTPy+~?d5Tm8*jdj='
        '?Zrl7g%sM0+CJ_~$f3@ug{XmGOIia;pO@&xC5pUe8}+0B5c|;jvIPaUcGla|iN3{lZ%NIWtIpIG%55sJ0SeJU=sibxBO?V-3L-E9'
        '90F7FBp<4bRYx&x?j=AL*77S)rZfbZmUfs`imW9QR*Gb(QOE@KAc?w4={Y9TLM&uDP4CIVJgq`YM@gs`k=}t^;Y05EyzluS`IX${'
        'x-HKE1`#Sq^**&CN;}$W40lLuVn=H<@RC4Dqo|J1BU0+Zgz9wb>_~%6&Z{R`Dq*RdLXwK0FI-jIz_wJhqe^f;13(U>2}!7%MBI@='
        'cYSqvfWAk<_b;Oagj#OWd)Ydw;W%q`a%LWeFrdby0w2N&*$)GU9@lT-11iL`p<?jc7uGBol3;!W2l3SOk5ikgy~U7H{(v%%w(d$I'
        'd<vCD&bLV4x@y$<yTvwuRdLM8`^#08nacYEIGh#>-Dx495b-nmHUYt9t4_<xC^K~%*HCS-mI)B<r_ps$;!!RPCLu;qpVijq)N438'
        'G&Q*<rr<UeGC&+h8HIn$CrVFkJ5VjI64+9jqg)sdko#6P*DEGt*hpoX8qW>xMf~hCaBZCcBi#*U<SNH7Br0~4cs1o_U`q^{lInH6'
        'uLF`*6Njox(urn@|NiY%{P*69|8A_V^>(^fsgr4|KIR8qU6Lv*yjhWmfp?G_vZwgB$&^(G0!qVkKdU^IvL%Z2s-ZEI0NG<b7uD1}'
        'bVNe*7U`v8bB)d?t!5)l9f(jQo}&{bwiIbiL41HarL5;P`le~q{Pk3(xvw%!d#l~O(%xRX3U0QuOSbvknkp7eiWPu9QmyvEktnN@'
        '62!A8V`WtvW8@<2Z<yX^OrCZ7r{W*)ukV4zMyXgSjHB}=7MxP`FQ-!Vjg_iU5COZ}?(S{w_1fD#%|`dA4_bT8+}uPrgN8&MWsU>I'
        'Wb;I)&?<jVqGsIHsG||h6?L|b=^PVv19OzoQmblnKzfG}!j$5RHbAho*tR0u>NIc6=O7tH;&n?go@WtNW(R}eqNtC2U7r%DQUvf='
        '&HjV96@By+lxY*DGJ|G0Gb9T{Krt|}6XlUmP+H{)vhS0S6A5Hl)mJN28j#<86-(+w1M#3+bJW{qHc4OAh{kzKRZOU-L~C~CCh=h@'
        'swgJ9tckM)5vF<4px;VWN;u?Hw=O)jzuicr;hVEDnHVc?)h=*^@d^!?#_69=h110fr<>~l=jO&$0_OkB-x4rmIZBOB%mM0%D5UTQ'
        'HQ#}aR#tQ;2Hy{So=W9;WaI;x!AzE@(SR9wb+qMH;I8UI$mxK;O5W9ZttnQG_Num<`lULmruM&~4z)(w#bD%$Yswryn9M<k(+c;Q'
        'Dq8vszAjrP#v1A~4LXQSY9LSN@w89=)bNQY?rvNq*!_{drXb(EMLsAG<%&#XC_gR#R~GU``33no`DOV<`BnK9`Azw?ytu=51$9GI'
        'V#}9`JMDpYEL@uyfbF^Ec5#;tLn3S2R6K1eo@H^4{`g+MEY9ynsdv0fZ(k{wiut#d#TgmVJ;|Bp0)B|0EoT%<?w7@baoz_ZuoH2R'
        'tBO9pzevmCtfpg_NBU#*yB>Y_^!3U+T93Bq)U3?t%HeKX@)QD54zmphFJDCR|N7<xz6>R(U}h3BQ>Ota3IzWNatq`rw^NfibvMzn'
        'Rw>C`cRoltE{b(lc$|4H0e}(@JIIj=5bHYi0V8w(tJx^<tFH{;>{eMUD!1t?tq=<7OQC6_+&O6wShu=y62<+>H+B};38;)(E{&05'
        'O8LDd`F;5V`9t|5`D6JLvYq^Z{E&vz+Qf<Xg<bAaQ+(Y?H+~(D>*%T5bhbWz`@8y6^B{cj<+NWcKs2>(*_qGjM0-(k{NKkQI=+@y'
        '^f~tfl5Z_8j9>r0vyjhtuTQ(>qP$DqEAJyA9t6lk0Q^OO`-=ef*M$7mtp<Sn_Dk|R+w!|pR+2xJKU0?a1rQ~FDSvfJcgWw)Fne*%'
        '7ROZc%B^S57xy9Z^krmXOF_)@x(gYG-1>f<TW5N#>4~P*+2mEmRrBd%Tg&q^FDm4-+pzJo=gG#^)k3O_tvo|NK0o6}b;oh1U7ep9'
        '@z0svEcsgV=|b`F4KGdg^m6Rbi!<uXLbJ}CCDM?mMD;HA^bsDh+Ug2VdtvgvO}@i?de`hlAM3Q_d#8T-XKcT4g6*;VY}0q<VBUEC'
        '2KPJTYoO!#n_mN+MQal08CBj#P<dCw5z}u>Bi*1RRIk)a$*a?axH?Hd!U8cI3hEg$-EdBvp6sW>T)U<sZ016BwCD(LSf36$il;22'
        'N`u?DLLGZ)2dY~YP<0ezs<Nr>SyXR{6fSt+tMrSNLpqS2edlB-lrPjV&G^<y1aU^4wK{YW$JC8_)N7B=EETOi@=~Fo65I@RcM{p&'
        '-?PmTAfb=#>3)H!u3b}oVxdGJ)cM?G>F&(kgiX!dZ)0`ysr@cpb`+1VDP5_!=vG4=?U7YeYQf0U4lyOC9;O<4I%09BM43O0DEAss'
        'ws(5=>VEIZo$lsG+v_CJ!|Ng>Te`YqR79DoXr9R^F_*bhJHO^MJHOuSOh@mAUDCFX_9o748yy!ZeJ!MmtSHfjs*3KE7`L59jC&el'
        '?5=iKx7xjSmjwBs0%div+PD+aM=^%`k5Ab_X!Q+6^{*l(g*tN@p%xoLsYZ|ly3%X(cDlKZrdk4JmYB}+v+0AqF|VBx?Dl^KE}Pr1'
        '()Q|8cDvi%QRdnp=^7VOI(F3ws|p*T4rB66U3Y|tT5T*k@=}c5QJPH)ceX)@Rqa1~15)4NMS6UY9*iDsdaTl8haMezT&2f8Jsf)2'
        '^a$wT(c_37DLr1G$EWbPCB{(9mA6P47V7dhn={NVKEL}HX_+cgzc*|Qg{3p5SBGzblDgt7Qr(}wo{&ww*LCOc0nDpQxHdhj4c@8E'
        'Y}dw3E0g|Lxa{!%N&bJ6)Ba5M`OANh$#vd-10tt=a{`h3^89Qfhp4@HGE19D&KBq&cbObq8Vfcl*Wo>6(hJ2xQd7KYka77h$wfb>'
        '$FJ$}tJ+yx-<ZFFyI#6=PCnZ~dB61!zfIl%VJH9q'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
