# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zmaj/.cyphal/public_regulated_data_types/uavcan/internet/udp/500.HandleIncomingPacket.0.1.dsdl
#
# Generated at:  2026-07-21 22:07:52.982459 UTC
# Is deprecated: yes
# Fixed port ID: 500
# Full name:     uavcan.internet.udp.HandleIncomingPacket
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class HandleIncomingPacket_0_1:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     session_id: None | int | _np_.uint16 = None,
                     payload:    None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None) -> None:
            """
            uavcan.internet.udp.HandleIncomingPacket.Request.0.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param session_id: saturated uint16 session_id
            :param payload:    saturated uint8[<=309] payload
            """
            _warnings_.warn('Data type uavcan.internet.udp.HandleIncomingPacket.Request.0.1 is deprecated', DeprecationWarning)

            self._session_id: int
            self._payload:    _NDArray_[_np_.uint8]

            self.session_id = session_id if session_id is not None else 0  # type: ignore

            if payload is None:
                self.payload = _np_.array([], _np_.uint8)
            else:
                payload = payload.encode() if isinstance(payload, str) else payload  # Implicit string encoding
                if isinstance(payload, (bytes, bytearray)) and len(payload) <= 309:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._payload = _np_.frombuffer(payload, _np_.uint8)  # type: ignore
                elif isinstance(payload, _np_.ndarray) and payload.dtype == _np_.uint8 and payload.ndim == 1 and payload.size <= 309:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._payload = payload
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    payload = _np_.array(payload, _np_.uint8).flatten()
                    if not payload.size <= 309:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'payload: invalid array length: not {payload.size} <= 309')
                    self._payload = payload
                assert isinstance(self._payload, _np_.ndarray)
                assert self._payload.dtype == _np_.uint8  # type: ignore
                assert self._payload.ndim == 1
                assert len(self._payload) <= 309

        @property
        def session_id(self) -> int:
            """
            saturated uint16 session_id
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._session_id

        @session_id.setter
        def session_id(self, x: int | _np_.uint16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._session_id = x
            else:
                raise ValueError(f'session_id: value {x} is not in [0, 65535]')

        @property
        def payload(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[<=309] payload
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .payload.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._payload

        @payload.setter
        def payload(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 309:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._payload = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 309:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._payload = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 309:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'payload: invalid array length: not {x.size} <= 309')
                self._payload = x
            assert isinstance(self._payload, _np_.ndarray)
            assert self._payload.dtype == _np_.uint8  # type: ignore
            assert self._payload.ndim == 1
            assert len(self._payload) <= 309

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u16(max(min(self.session_id, 65535), 0))
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.payload) <= 309, 'self.payload: saturated uint8[<=309]'
            _ser_.add_aligned_u16(len(self.payload))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.payload)
            _ser_.pad_to_alignment(8)
            assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 2504, \
                'Bad serialization of uavcan.internet.udp.HandleIncomingPacket.Request.0.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> HandleIncomingPacket_0_1.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "session_id"
            _f0_ = _des_.fetch_aligned_u16()
            # Temporary _f1_ holds the value of "payload"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u16()
            assert _len0_ >= 0
            if _len0_ > 309:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 309')
            _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
            assert len(_f1_) <= 309, 'saturated uint8[<=309]'
            self = HandleIncomingPacket_0_1.Request(
                session_id=_f0_,
                payload=_f1_)
            _des_.pad_to_alignment(8)
            assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 2504, \
                'Bad deserialization of uavcan.internet.udp.HandleIncomingPacket.Request.0.1'
            assert isinstance(self, HandleIncomingPacket_0_1.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'session_id=%s' % self.session_id,
                'payload=%s' % repr(bytes(self.payload))[1:],
            ])
            return f'uavcan.internet.udp.HandleIncomingPacket.Request.0.1({_o_0_})'

        _FIXED_PORT_ID_ = 500
        _EXTENT_BYTES_ = 600

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8xb0tR0{`t>OKcoRdS=h`boY!To0e>eUhP`twd@`5(&O<%Hf`^EskLHIDE~4cYc~XTjbYDpk=1s;wjbn-fdJe?0v;Mk1MUF4'
            'Es+xsIq=9Mk38zABY_|Y1LVOx7GQG9U)?>!8IiOt>)|9T0piSbRsHq<-~XukIUiT#zy6yy#<G9$C9h`$hSg{V%r|w*{6cSAtkLSY'
            'w&w<B$kO=CHD;MMzBO+3JeGc$zWlrN&(eCVv`oige#*z<GoOTh)CnV>jZUew9Nk6{%}8JB=uX3QLgqUxY($3Fn9&`>V%Htq%5)ZI'
            '_0H!waFhKuVnLY3T5E~<f$2IzzWS@;{g){nqtaibzf0p&Ej<i<vmJ#jNI%8RPOxM!D~&53n#?i|)vL7(J=9yF(D|h0o-b@SmvF|p'
            'Upj%g=rH3tnz6|IQCm;7+Gg0Yn6nu2l#ZkDjvj<9+cj9qpN-GY_63P$jSp}P#E`J)&(oV}{B$b_5fR-th6SxgZC;CO0SkovEz?M2'
            'xn;PWH2%XaZU$sQSVRJ@TNdfKPN<s>2{|JH;!c)yD`NOj56Q9~kSJgVY4@^m%kAhEaZm%Y%$Y+1<{0ROY^>w@J_|fIf8s{rqKj{8'
            'UgjZ`(w}FeQu-opfCiC|i)n=)Nv2({z_N+Twb@Dghc2=8u*0+G`NjdOEt?@HW*8JRg>9@GHd4gnnH+IG5nnvP<-V`?()hx!bbN|W'
            'KFYAXDxQw|>`aSU%w|rQ#{j=rNPdoL{1ShGUq<-jDmoHvH^W{ESETrC;hI(k{gH*^xbS%@376)}<yPAY()gvms)x=+t;4%Nr}61u'
            'm|?E)C-|{YH7>VYFOA7bLV}*%b}bXb;v6vBMIb^9mybQ>>!Irp=WK_Ym;(Ig@iQN|PDc-!bL>=MwV3HMM<f@{fAU6TS-RglGE-?~'
            'ZchIyt<&)&X!END7}s#sg`2vw$Zj%^h2}{recrP5uD}*oe3U)q9}8g`3d;b*`hZy?-iUb{)mRm26<N9vKqWDEETN_1wVb_DiIx&7'
            '7tbn#XS7V^gev*xl6bF<jL`~J5~>yJsz=7Cih9x7U_Cy;&!>)^N2|1!(9`*tCiXgW;yikao=)f!BXaR6K6~;j*U&TciG+?9dnEL!'
            'uboYwL^sj1M|Q#ye17g5t*1}Xvk84VpDW||X|eX1Z@iYCqfaOF{INRVD2`pYCt36vdOo2OeWX#BXYYAEy+9`t`n?l%!WlSz@mtBI'
            '&(iND^!p=t;V8=c!MB!2FVgQP^trFp7iZy|OZT-0{Q-S0p=5xq(E9oNmPjvAlF%RKa>!TdFLr<7f$T@0r$0>S<^G;Seh?_V_`vp{'
            'FVM>ged%jGgDVKm#<@RwpnKC7=}QT%_w6iv_VNSYgZ_xt6Z+$CY$vY3`9FCmdeE2Yj}tn1=-bOEvp($KS038F^e1#Op^baO0axLg'
            'S0AcQ^cC7jX!9@*>Uku*_Rx2wuhM2hU%zKWa3!vL<B{k`U!$)l^v$CYGl{aB{iwO}$aJA^&^HtM*0;h8SL52ZAE~bN3Vkb~Q=`$<'
            '6!G=WBiDnzO{Wt2?zhGcCE)t^z7xIaJM`Uz{`BNHd=vMW60!KR?@T}X9{p)T-@h+>Q3}fV`FCmq{TY2fq0>iV7QG)~$IiN*?qt7c'
            '$Y#KpMm5mz{Dg6hPQZjl2@qTab&WQmsnIEz(&#iyYjg%?G&&2j8l8hVjn2coMmcbedf;ia3tf$_z=}p!VO66EBpO|VHI1&rx<)r('
            'L!+CpsnIRi(&#p9Yjg*8G<q9uYxEA>(daJhYIG0wG`bJ_8a;pm4aOuGtAZwhR)uj1#;Y(P!9*2^1f&Xe3F=j7O3<vrlmt^%n3iC='
            '3NsSSRAE+v*(%IQFjs|n3FfQ7CE!)?B=D-xm7rUN6$w_Vuqwf76%q-ODy&JcR)uv5)~m1~VJ8Ng5^PDZEy0ciw<WkE!L9^*66{NG'
            'fa;Y%E5UdPCQ3j`P%lBV1XCrLF2PI*W=k+vg835g5_l!(mSCj>t0hQEuvUWg5^R)Uvjkfu*e=0N32v9*P6>8Puvdcp5*(CZtPENi'
            '#>+5K22zH48JcC7D#LUcX38*IhPg7#mw}hTD?_&oD`i+MLsEvdGOU+jqYRs6*eb(z8FtEWy9{^Auv><`GVGV(pbTR&Xflk;Fd+kx'
            'p)NyHhAA1QWtfp+R)#ql=4IeAcrtWlSdn2>hD3%n8P;XkkYQ7XEg80D*pcD340mMMm0?eYeHjj97^{F*f$<7VRDe{VUV&x>rYbO9'
            'ftd=-R$#6I^A+F~@G8))z)A&HE09!Rtpe*6*r>o}1-2@%U4fkn+^)c#3hY*3uLAoOIH<sw0-6Hj3QQ<K6sRlERA5ShX$58!m{nj-'
            'fq4bE0-ge01y&STRUlDdO@Va<HWb)YU`v5*1$Gp;t-u`xb`{uDU|)d)1;$j+R2WxbLIt8iU4^C!Qz}fWFr&h(3UeyVtH4$8ROqU('
            'qQa^Qi3)2ftgEo0!lnvaDr~E;qrz<!?x?V<!k!BIDjcXu)Mi1O|C)~T-@sOtfBJu>-Pc5$_qg4E1nvHKj>F@2{~@&d*evAeKG1fb'
            'eBBk|A+-Bs)DQn}+kJBQE1Ex=c3;?h870?8{rgAV?h8!n{YZG+?%&n!k4DVncK=@6{k+Q5acul?yMG_;ets%FZucKWyMI^_i*}#?'
            '9v@?e|5g3H=<cV!L4Pm0`|bnm@3Fhb7XN=qf4^B3E&f*ZahLzN%YR5+zWAP>*J9PvdzPykDSv71Z>6!ZKUr8{9YL8P#XvzT5v-j7'
            't7O6Tmv!G@23hc3yC9L+Zpa9CgODsSzpaO+-KhQY+APUAEJ4nR>GNf5*Uwlo4!P2tBJEzt0^%<8_awI76Z;sx>v=hWC2;MW^&;lg'
            'I<9R;j@ik06omaYGCe^lX^@+2f%$^oa`VFv$lLF{Ms&v@ufO?LQ|OEzi0QmyFfZh&@RG@v8?_I59@j0h5cz0^Pcqt7kaKPHu4zYh'
            'VE_rtFEZkc&y1+U3N{Yf(aZJ-eSKlU?2vYZxH!bkDM5m46Eteq5WGcSw+j$hx5Ln?jQ3N}T!iuAFuBN$@I^pi2Av%0g2f}qO?D<&'
            '5OY|3ZitiBYWH&Xm!N{Y$j|e?<Mk*$)k2GXCWt3Sx*9*xS}?oJXnC$53Ubqp_^DRlMt+CkfW=y#9`aPgMaV6)oyOH!H!!=i;^~)Z'
            'J(gZgW0|{xVkUoK>!0D&Mkm8CjW2pp+cG;XpDjj~*zS<*6{N9}Gt$yn>vPi5xEvW?8b5!f**u<`)@;1i5cHcg6nw37Ev^TspfBh{'
            '0rQv44og=ta{sbAHkO5HpC5&o`6kB7Z~z9lDi2tFBwPz$T`!a(B2dUjS8oVs>p5Sln3D6Niil}P=-F9|>4Av;BJ9L0gDsd&#=ObB'
            '`jxD$JTA#1bC{1p-6dfaTkfy)29rd>2}+pdE}ET2t#+7|nN$P@!v!PH)=^)b6zJrGzMjQ)mT&r~HkgYphL@jH!aipi{|kfJ3DBZ|'
            '=!W5o>1~Tm)^y8qmjx3o3v020*`DS0aC6^4{czt-2a`*8aAS<6P)HE=<?jn-+fel|M)N{QaNMxJDKlz0qIQE^HH-{VRG~MCaAU^%'
            'eNG(e5}G-s>QFP?TGo3(!EG~0gg^0v&~C^tM>VOr9&-Yc1!yJ~RrW-tM8c!2FeehUOHAXCW#3!`cgYj0Jl_r7j%zi@^?a=F5Yt(5'
            'i@Jp+k_9z{Wb&@eCg@s^`B;fUQ77CiT$k7}OhF83EI@-QeB<gZ5(;M#)3%vmVh#$t1gOipDa@$}1B8!n-TEl=VAnH!hVgVg9I86F'
            'AS+PllyEf8hJssw<n*0FFcFqSagM^=+^nMXU0EC=LXztU3~Ga*3rvh5b0IHo;(bOA%mA7kuC<tMgCZ-kgfrck%t~(?OIsA=voH*V'
            'YjS_wbxdGI6B!-|-+1nT7-@>i5Q-&5VhAPihX4&{E}2<AE$NnNAc#Go^FYnat7wO)Bk0K!ssur7aTh%ZBD)XkAsI8kV&w?XT?b+8'
            'SSHF1a?3>4GISWr0;D%Me=`q<Zp~n!h!Q8ay}-I3jDlW@s%7~0gsHafdHtLzj+p_)wWwXDpND?#QX5ZdaayC!0eVE7WFO|oq@C$x'
            'W@bg0?S6KsFAKxW{P1)!(QLF(AchM0;sg=}xUaxye2C1c<)-JDyjut#!EBVo8su=;2tDd50^r(>Pl!1Ff{}uEeRfb#5Y_;_w~zx{'
            '69irTh$aG=$)RM#eX_LR`ciiOV`8GVwzxoGePaVy2T6FiVeU0icJM-l)l3wtqR<r6-D7gPZ^qZNhy`Ca1G_j<`VpL`TMZTSUA@Ce'
            '$7jNQ;xvowHUc9;#COGEjf-%1JbW+;12F}|4z(9^7jz5<-F71<%MNZD;$|aQ>K5zf)iBq;Hk!6sDjmX?*A`RMVv&y`Dve<rj}}JU'
            'JUnDn_YWgXM$`4hUCBb^EewrAY(!COqpgPEe~T)YAth`MbE5MQIGORs(WhtJW#LlvJ!3_j4r`s;md8SV0I|ceUF*}T4@-kSII>7~'
            'W=~>%nCOh+ZW|#Ef$3-LX>`{h(FX#u;}`c>@L49=zzZu{lm$-hIMsyfFpTi9%5N^&HSccJOeYALxYb{GiVJ9vA#(imBFAgGv1A6h'
            '+xnFjuL1(y6TH(%<MHe&n*UXUBWhaq7Xv3>0-rwa0*JTE{+}nX_(FC!ZG~>jcik`(AK(RvrTm}j{Ga*1@PFm|{NMP$i@PG9;_v0W'
            '=J!X)(NE3_zc`CWNYOZYIPb%J>2*QF9z6Z5iv7`G$}nqMP_SbSwaY}OREmmkQ1Sn#IO+E{@WC(g?^Ox^4eV40k3XA0p;U{G8Ol2}'
            'eu|&w<NPV1%6VRA{O^Y^_xvAL`Q8owk9Q%!|AYT0|3iku0p5@KfARmmPw+pJP|ss<j@4Fn4+>M*J{zCMRwMtz6~848XneVwtWWqQ'
            '{&q&wKi);d&<|rwMrrQ1ig$ksbERWB?EKd^5YFwh0?z)I%|V81<_9sjd(5C%+V~$+$G{k^GXMY'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self) -> None:
            """
            uavcan.internet.udp.HandleIncomingPacket.Response.0.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            """
            _warnings_.warn('Data type uavcan.internet.udp.HandleIncomingPacket.Response.0.1 is deprecated', DeprecationWarning)

            pass

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            assert 0 <= (_ser_.current_bit_length - _base_offset_) <= 0, \
                'Bad serialization of uavcan.internet.udp.HandleIncomingPacket.Response.0.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> HandleIncomingPacket_0_1.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            self = HandleIncomingPacket_0_1.Response(
                    )
            _des_.pad_to_alignment(8)
            assert 0 <= (_des_.consumed_bit_length - _base_offset_) <= 0, \
                'Bad deserialization of uavcan.internet.udp.HandleIncomingPacket.Response.0.1'
            assert isinstance(self, HandleIncomingPacket_0_1.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
            ])
            return f'uavcan.internet.udp.HandleIncomingPacket.Response.0.1({_o_0_})'

        _FIXED_PORT_ID_ = 500
        _EXTENT_BYTES_ = 63

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8xb0tR0{^8{-ER~(5Wh4B2?PpJAgO?sP$W2BmLSwhR7gmCNT4IfDL~)A@~(#)!=Amey{8;fBzP#wgQX&6c<le#N5*>zx`d=J'
            '-Iuj@#xwqX%zkKp`R7=xdE(`2th_2S;lXKH>i04)ArpliR@UnP6i+{dQV)5lUW_ZC9lG(6wx|=23vCQI!d5)}Jh-|DwS)aB$ApnX'
            'E^(`tqe7ZYn*h#0$ZAz(kEKy1JTcr#n?YX|?>MjlzOu&inRzh+=e0Gd!Q7v_>mBO0x-*~XBgF+FLvT8;19*BxacOEV^6{kgR?1UQ'
            'IVdC}pzZjhc%wH#iORYlw4z>I6yDaZ01lKODjAUCTzZu{r+A{zJZ$#U*Byp5bCY5lZ9>(4Ka_7dH7mvy%97&6s?JMY2nU0@Oznh{'
            'L5jefc#6j-Brvi)8Ys>(5frcdwzhUS9c$UGEXhNGHWEUVo-gRYgrwI<7r=<xLfL|1i{jY^^h7+vNr{)ve>6UKSX0jXrUJy3h7b{~'
            'aMp&VzON+r#S0z0h?nqZ`~@%LYIDK1$V*0gZO>D=4x$7z-~yh}9N1Glbzg_4&Hg!WcWo1Ah2^`g9#zDThq+~%nU8fCT6Sz;XFRLG'
            '$za{IKMT~QBK#ws=}V;;;CD%QFGYKGSxPrP8088hS=K;*Q>WYd>~r>HH7P{h`8sE~%o-aqE#zie%!#2@tbICtQov><O=H_$o%_7b'
            '@gy$bDLjjduLzg62+wchat~JyaEVv&SG<}S#cSJm9XojA|LTZqhv_xPR}AbETK{(@F7upB2Hgn+srZ$gOGo`8DwmS=h%=U6GR%Pi'
            '^@J}r0Jr}yurMVdbyt~~Li&)HVi&!R%l*AV=~(uFW9uozqdxOjy5%|H1LKoUO&8i`I&b6eO%J?-cc%nB|G=6w?&eTu#1j)^@D!!-'
            'z(<o3kCV!)tn$86D;v@bU;`=$`Y4;do2Y+}4@}pZ|J+F4?cr0V7uUDgG`mj1XKV=YyTPA+_&%79W?un#B_>U%1poj'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.internet.udp.HandleIncomingPacket.0.1()'


    _FIXED_PORT_ID_ = 500
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8xb0tR0{`t>U2q%Mb;bgV-326Dv}8++72E4rabTN*A;+?5$4=-<aj3aI3MwlZcBUP0fxYA|4eW0AhXg#+8RnrKw%xQl<LwL|'
        '`H%-b<bjWT<Rc&Ts7F3>I&DX7la}pFf6m!mfB=7F{kv_X8Ii!=bI(2JJ3sec;={7|xAX7kl7HbVPEYsrcD3Pg*VNkPms+#UtBsc3'
        'acs}@c^sbjoV$x=i{I=yJpL+v<CpQD#+C4yhRc5uaL;e}^xVjW&s^ngvx8IgQAw#`S{8Q`k<WcMX!(JAKv}V2X&qdu7HEqt&8nJ~'
        '&s~fA)j)Tu)0(BX`85koGOhW#*7^bmZlsIHq0(67u4md7>6d?=z5Xg@IVSvh{7W>yq4~aRHUpn~@t@#g$9O!Dio@ckCU5Ke=9L?|'
        '=4+{=$4z%!^4(lSi8DX5JagXS`ZaW8p1Y&Io@g{pztQH_yl=#843)PuM6qM*h~mrP*?M0QO{-qPF`yyx=+ELCark`0^AQov)rS?W'
        '1Wn^qSoXL_{x?iL4#kFUx8m@3Hx1KM=g1?~GqiSFZP}KunU?AsT=fulbx~^v9N%ibx}<q(;Bj4T_LA|o-O}2sg%+qw2Dem?TRKJ|'
        '8Ee_D%RR?VpV)yvZ{v%ylSBx$^yNBels1nGphN0UGqEg=YGPe#z><l^HTiMt`?lKA{FaeCPZ#!hdCBw*)%3kgl6>P`zZxSRFQ$ka'
        'FNNoi3AyWPy*NDga}A&3lg|<?KcS}wlbyGDhg<z*S2NA8F~zuGRE#$e{;-6BMBh!n7sF*CJe`H6kwAZF;uubRoe31ubh_ARw!Juf'
        'y>IG%aM5c2;QKf{`3I(-8vHrF%}fmo4cm!B^*AM7uhX>KCZ@$1;2j%*@G)I}>Tp-{ZFjh4TZV}xU|bDfxMEu^&F9vUqU1G6y4<4T'
        'LitnIgLYeUdxs>YMiS=uZ{i9Yi@c`sX$HnMoOSMoX3g^(+~K}?oJn6aI$D>o#TkE?JT-2TG6j_-0Ahc@Dxnu7w_XZmDyyKakpd=='
        'Y%XH?>~|sg%><T@n3z2)4xX_B6C)<2@ALFp9vNdrCPhri=9LbOF&XV*<-vS>g6~fpDaT5z9I=z>m_lnkbF3UY!A?f(*%7_?6rY{C'
        '>m2qBdp2TY*%}dh?rWvlDGU=keP|^d!RKf0X+C?7osQV^sjP_OCu!~r_dJ)KVb4eG?2$I$D2|=GFJ0^fb~a+;eWcNrZ{7ENc8-ll'
        '?8RekLJ1r{|3G@#x7dpj`}PQ4IEwmSdSHF*Jo|RUUcRfnD1|bwJk%QOCH8W})B(0+^{Wr9k-fsyh<zv3qu$MaTK%<0vL1VteJ5fU'
        '`fCowfl&JHBU^*L#x6wc^{<T#&QMVrWxw}G*Jj^kuScxX_cM#x8;^Vq_B~dK*qit4C(c0mw;qcf><#v2#3uG*djWM;hU0tjv8~JA'
        'ViOUo-WLuy3+KH3SZ!h#Sv6v{{XD3onQ-Z`ugczLwTQiQ--zH$ocH}FVjsK2-ig?|hcjjZb=Ue?bNPwc!oJVmjo5n+gc;7px$i$w'
        'TiIpyUc@Fxv#Un=^}!RjgT2otBlh6~V}}}W{tvzpyV(cq!-#!!d>+1wYfMrue*BHu$9}**ir5by3SZQMI)3zx`oKPBKaAMap`69&'
        '2Y6%WT}QK$KQtr~kW-if3htjUrm%4sSC|SaPJ)WUYEV<yBupx73Z@h`4buv%LtSArFr%<pm{phohQb_h6xM~V!j@rKVJonrum~cB'
        't-`9p)?iIx>#(k{4cJiFCTuEf3$_%t4ciL41-BG-8*VFX2X+*;3%d%t19ud*2YU+S1jv;@5kM)ym;hrX7#Co?1gZdP2`U0qN>CG^'
        'R)R?ZCQC3Sz*GsQ1(+^DU4VKCW(1fi!K?tYB`^dqO5h0Kl%Oj>w*<=qESF$KfRz$N0z@TP6=1alYXYp5U|qnQ7;FfzDZrKh+XCDY'
        ';I;re0_+NKM}R#vFAqu{#_}+p2Q?3sJk;_qnTM%7Oy{AVhnYOg=E2B=lZS2|mh-TZhbRxLd05NCdLB0Nu$hOgJZ$ITRvvEWVJ8o}'
        'dAO5@y*%U!pcG)N0OJKv3s5OQtpJk+m@2?@0qO;qDZp$2i~=|X=oVnP04oKE3b0y$wF0acV50z=1=uRUb^&e`;C2Ca3b0#%I|bM)'
        'Ku!cjgfS7uMNmbkh)@$@QiLfHrbVcWFeAdO2!;rb2wf4DMOYCb5@A(@H4)ZD*bre;ge?)aMYtuxZ4q`v*cIW92zw&ril7u>tO(;p'
        'P>WD0LahjsMVKnWbP?)Bm?^?+5sV@@Md%h`xd<yoh>EaUgta297h$6an?=|v!gdjE72$Rfc8aiDggZspD?&~JMS?L2#wAcCs7O$g'
        'U{Zo938p2eOE4qBtOSMxjs#r^mL*t`Ad+BJf;9=&CD@Q)Q-UoCwk5bF!EFh4B-oYUjs$xW<YZ7}7?WXK233ZN3^f@hWtfs-T86p|'
        'GcwG|V94Oe(3N3Xh7}ni8CGRjlVM$k4H-6N*pgvehFdb+mSIPRT^a7kuqQ`BlY32LmW>%2Y?h4X|C#H)Lf5>f*Zn7O-5*PFczWG`'
        '4A*_UETrf@((AtZbw`NDaNSo&<M99Xy07m4iRSm_x=%h|K+ToW`2JpB_X(3qKNFr__YYk6M>FQ>b^m^^`)QY{;MmyH>;6Mr_tRbJ'
        '>2?1}T=(}oVs_m(evOauhJUyFJ>Bjn@8Nz=xBKoRyx-&P9<TWSOYZj@CA#8omY&}7pWgBx(=DGq=QmD;vZM9dwx-9%TQk2Aa=9PR'
        '&G8mdX4GsTqm>YAXTU0%v)v`l)w!<DxppTbk#uaItA_3Q>LPcWns0Wh<)2-xt0{-YOF1!pzD&n<6PApnUan25&7RLa)t>9Gsdls;'
        't)siP<D>)@&+eqG7m_Qt>`o`J%vQpqQ28$c(;-SpRlULIxJ&ew8=qcL-~Zr}s#&`F&b#l`$Yy+_n$|^~JHCMiFPeO*TE5bA46Uus'
        '1unYbstN7NOSv{$*X#tH%mLLizf6cTF4uz=&)7KVM=x2!ceS}Wv!ylz#KltWloCW_8?Rcvir~$=S|<a6cUv62N_amR&4rxzhsi~D'
        'fWHU=(`%(rXDl8fH+2%lM9ksgnITSAquEQ@Uql6Y(>QPJ8W)4`L<2o`IT26vcqM$cF=uwU-f(Q!CvwyE@VSO(2X2ewK$|xl%{OAo'
        '3*Ts)%{VO8ZO`o1>FHN-B^2I{L(#B_VkUms(H2m&+Db5t!}CtiY@4ly%jbhOEw@kh^5RfR8EJ8-^f_s9SO|0{4qv@os~ycvt5q*m'
        'iGCCN#Me60Ff<PhbcsIXrBu3j1vB@rOSxQ<rhR@CV&<BdE5ixs;jA=awUKnqVs$MuN~J_mKl|i51zSt`Qkh7~i^?*l8DM1VZLWEg'
        '{aM<Pl+Nc&D`DQGQN1f`E6q!Fo?F~SrS>9u#h3asoq-S)98tpB_Pp7umdpE9nP^2|FkLY7IvU!msTn%ypsOXhoz$B)Y7N$+jp^m4'
        'l&~*&!vDf#wmkI6Q#D<8Nxa$S6J@R4wwH*BmZUY!;2o!J_i%AnNBeNyRtt+uvv6U|C7(2qf9dOt**4TY^wGK?4VLZq7v*|6MYK~@'
        'KhgCBQ8b}9p%Puvbo-n*w8b}5O4Yt)T6;<Bc^S7&R|EWsZ^*i#xE!{mY&+cY)FeR@wP><Kl@d@ydFD<)v`Z{wpC_MOcn9>+EXTEd'
        'yJfel>a}#N9}v@8w6ng2Es}d>gk<7CWvdukhr8H`eCiW+lCF#V2&N#WG&Z0?7ry?<P1UDhsb;6cbrWll@FGx`G?UyZlLHjvn>Rm8'
        'BG`3Imt#I%^M|?)PDmOQ2E`xEv!UcBkgR@CR4jx=YR-Y5x|?*Aekij|gf!U}VNf0<oo8YWnR97#qt^*JFac;{xYuI24Vo-fiNQ5}'
        'B5A!%Y;A#;N?{sMXwrBb*e0-}QH6UH8^<0HBTecIK26CAgN(!<1R6>%nn^t^YHd?T5PM|vz|177=m+%?jN~z0LPczG70vU4P9N5N'
        'GNy;k$|BHh3t?=vP1Nh9o>A3u3>Z%mq&L`qlL-5ES?4}wiIw`EVckzgqL-p+3BEmYwWB#szh<&+W<YVxdY9>@sh@_lgF7|t)@ZYb'
        '5uu&z({!8cBsQ6eTLD(Pn{4V!<d~Umo;DU*2R$Uj&>)v~AZoyU14i?MDyN*fo?`N0rhEjmQ4*_{!qGwK(N;=;tJgnQY5Vg=8s4?~'
        'prIhF9!7621-48CUG0!1gv`WHG2%K&Ss2=4vj1aYqO~15Kwy9416T(|xW8Z;HEKI}pu%oO%_?g&nYevKP50gSdKNM9brZ0&Ev28q'
        'X}OirFxS>vhT3vDg^zZ#pwmQPC`DYGHfx-OtK;T_S?G}nrX5;OvU3`ygVwPFE2$2{)ahhHZ1y(qrrj{LzdTyDNh$5am-ZHudNI`_'
        'Wu-oh<Kf1Li~IYG>i%Yg#c0|tot4^%d>d0^9~)|FP4rbK{x@~G1S#^_Pl?V$;3Uo;MW3Fwmnftdd(N{w9kx34EzN~=1LFH_yWFQ$'
        '@3#hRuw|*qo;`u}VPY_{vu%Jlc&3}Mr!icELLVqdwqIOh&gF?_9S^MNQIa_2qfDdFVH)9Pm7ZLZW8Oj3Ow02*o$9Yy*#Xo`5II^r'
        'tMRg?FPdH&wtlC@qX40MOmwPoIF=km({Ddm)YFo03><$5eEz5dAf7J!Ur*rSx#Vox@a=|c+kT?n!vhkJjen{b|7`q=@mu3}#=jc>'
        'MrTFiV`D1iHD4JaN1v)wT&(#+q-Y%7mt*PF>qNsIJY9Ge??(fXVb(NJutNo{OH{{92(nL5@qZJAetjJu{3QKc75fNmmj;g)UP7fz'
        '362;_Z)nDt@tpC3ah6OuZ(QWY-whw`jlW+p{^7duj|UJi_Kbfw{v*NRKk<BQ{Fm|H4+;K)gmxZ*b0{~GbC4gy*6HvpUNzD$uDA`_'
        'pz+s1vc76uFg{9X`bURo82Vw1)lr)JA7!up7-sTEa@dX8>j>x8X@ax=VY8Run#6$yca9iL=<m-q`rnDj%$Kv(%Erm;)v55(eSE<t'
        'RTlRnNin>)$c4H10Yj$@Ry{U$M+V^dEJuh&(lv+qojZ`N3yhY!Z#Ng}H0`lDx^NMn!=A8ErSZp?i|j{tNyR<kE~z-4KROjL&nowt'
        'XYqcc7<^sFQ0Q+w+1JbB4CvwS^DO*?AUPE(?jT9~LTRg6_)C1VutGn6ML+(E#*(PQZ-u+Y^)DX0@f;h;pjrJNf!mFMayI|~'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
