# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zmaj/.cyphal/public_regulated_data_types/uavcan/primitive/array/Natural32.1.0.dsdl
#
# Generated at:  2026-09-03 11:10:39.154752 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.primitive.array.Natural32
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Natural32_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: None | _NDArray_[_np_.uint32] | list[int] = None) -> None:
        """
        uavcan.primitive.array.Natural32.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: saturated uint32[<=64] value
        """
        self._value: _NDArray_[_np_.uint32]

        if value is None:
            self.value = _np_.array([], _np_.uint32)
        else:
            if isinstance(value, _np_.ndarray) and value.dtype == _np_.uint32 and value.ndim == 1 and value.size <= 64:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._value = value
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                value = _np_.array(value, _np_.uint32).flatten()
                if not value.size <= 64:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'value: invalid array length: not {value.size} <= 64')
                self._value = value
            assert isinstance(self._value, _np_.ndarray)
            assert self._value.dtype == _np_.uint32  # type: ignore
            assert self._value.ndim == 1
            assert len(self._value) <= 64

    @property
    def value(self) -> _NDArray_[_np_.uint32]:
        """
        saturated uint32[<=64] value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: _NDArray_[_np_.uint32] | list[int]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.uint32 and x.ndim == 1 and x.size <= 64:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._value = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint32).flatten()
            if not x.size <= 64:  # Length cannot be checked before casting and flattening
                raise ValueError(f'value: invalid array length: not {x.size} <= 64')
            self._value = x
        assert isinstance(self._value, _np_.ndarray)
        assert self._value.dtype == _np_.uint32  # type: ignore
        assert self._value.ndim == 1
        assert len(self._value) <= 64

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
        assert len(self.value) <= 64, 'self.value: saturated uint32[<=64]'
        _ser_.add_aligned_u8(len(self.value))
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.value)
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 2056, \
            'Bad serialization of uavcan.primitive.array.Natural32.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Natural32_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        # Length field byte-aligned: True; all elements byte-aligned: True.
        _len0_ = _des_.fetch_aligned_u8()
        assert _len0_ >= 0
        if _len0_ > 64:
            raise _des_.FormatError(f'Variable array length prefix {_len0_} > 64')
        _f0_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint32, _len0_)
        assert len(_f0_) <= 64, 'saturated uint32[<=64]'
        self = Natural32_1_0(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 2056, \
            'Bad deserialization of uavcan.primitive.array.Natural32.1.0'
        assert isinstance(self, Natural32_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % _np_.array2string(self.value, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'uavcan.primitive.array.Natural32.1.0({_o_0_})'

    _EXTENT_BYTES_ = 257

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8000000{`t<TW{M|5*F`toQo4Dahprcrnx9>D&^j!O<QdPEWDVV#GCF0`?8=Z>D1&dMG7Qk#03ht54&)H1M~nsefOh(h9CV8'
        '+P-<;{4+Wf<%`yF5<9koZS5D4XXg9nn>mM+#xtY;_;|F`{o|wU>1NstD{jh?zzc(Ky?V$hZX<5B<21;a<VU{Fl1?M*B<!!#Z6@dB'
        ')$iqZvdj%P@>*nfI^I;niz@9TXa!j?#VTHsc+-_f9$~!j)=kN6cZwxx5J%E4aqDUCdQO4@rT@t9B_DLXEK7oVCu6Dnhulilnv>+l'
        '9|IOP*VP<yn_lL*SuT;E-2$HLl6>T;N2|2*XBJIn{vYzy{?v}REMzSfWj($v<g8^Z`S9POG?<K7^G{L6CRx(YH|W-b%niHYBse6t'
        ';iZ||iknROXZY#yRiYeLc}O<QO;n)LzvUCjPr7O5MNKbhZX}xR)cF80wY^4=O-rcp6FrmrO<tTrynn6`;g5ptJN^Ywa!UVFj@I3J'
        'm`Z+mHNACm$~61md&v)f6=X%xzNXt=dR%kkHXVblNYd$6Jr08g6$x1@rs8F^`;Xf!@v=BsFOumt{D8L9zr{~IjH8B^vFL@adD6LO'
        '!Xi2=W%57vs1t@>GQG*ubf>(q!{iUL47Nz?{+(Vi?h$I_i5E?>C#=n~U@J-ga$DXrDlGwO-9`Ul&gBqSw|=c4qD{&#$PG(2xAI->'
        'gkFvZCHE}}P<x+R_mfV&DnRe88Eb2xfiA!-?$!L->a&3XrU1K#8`xw6i*kfRYj|3r`@t9b!2lc*aJaD9d8{K_`oSO^7I3tWmsV-*'
        '*h?{R1da+A>ghfHN?$kzLjq20ibED!AAT)79ETGEP8Pm8*$?N~Q?HGMVK^z^^b0kRm24y1;(}9fTEIK2btWzEZW|9H@Q#2pTWTT?'
        'vY*`%FT4w91f1)u7g>q#{EqqHESwYY-b?k87x|37Q4BZ_?+I{v=j;79=7LdruHiz#<Gf6H9`}P?i3jh)1pyaVV{X`iygrw9Ee3o5'
        '7X@5?<(?42A#d`%va7M-5?mHgUd@x9g#3(M-Srr71<C?GeC<35LH-}@i4M359}2j(zPA^Nv%GPCKi;#r@DW@SP}x=;2t}Cco@#=R'
        'p(5aV5o0KS-frx9JgCBT0XMf@3qlg^*1qV28*o#=?agQ98gXA=Jui3mO$*$D+XC+HsAhyF>?ixG74E=Y0r%G5FXe9C=pA!^-*vzz'
        'a8JOeJFXou5dO2bq8skRrve^qeGYF^jC=W6{QRxygU{fBfG^&tzQjTtU%u5G;B)vwK&@A6(V@1GJ!^YWw>d6WXRxH;jDjT<XH+a{'
        'IHO@n#~B?b3|uyF!o+10CoB>%kB)-#3OXvztLSJruc4#kypAPuwQ$D3l8G}Wmgw4o8Z2T>!9@jYDlV#6({NG4nvRP)I^=5Oyn&91'
        '^CmhL&RZ}6%Q&InvVs#TE~_}9;j)GkIxg#2GjP$snu&`h)+}7KM5oTE+j>kb=Q!H7|Cj%pZphAm2k&t=WFK@x-CuyEgKlU~x*>a)'
        'yCLUQ@7X=*hMfK#_|0}hPVs+%-&Hr1=X|ldy9eFSYByvPs(jE5ZR&>l&&okJwB2r~c)yg%HgwPpy+Jord><WjL;KMUQH@2%pQB4G'
        'Tev_X&{l9(fmyUwoK?}*a8^TG$5|bhbR08q$-or_$4vB9TrzP*#W4$g4VNrZuz+O+7Zfb3xS(QL!vzh?Ixgtw>$sxB7%btKf=fg|'
        'Xo3<>!!aFgVx>?9+9uALXj?dI;R*#IZZa9@Qz(lX9PnWUeTrb<f`Mfd7ffn_@)?nDaHE((aougk4arNgQ}_7rhKZ+JpDt#p-%0-`'
        '|9Hv=-6m@%EFXb2<#T@2{U&(Enr=HzGB;?-NBp>(#+{_W$PhBO?Pb2?R{jwNb;$?D<1~0Sp0CbH{`aaMw^;StmiNzUr7_+1y|CKu'
        ')We|RCTy}3=0Vnnr)jkq=T_H-o7L{vw7NFVt=y<wujHdX*_}-eyS|r_gd`uArYxBX8caU-fA)XjL*1;3S#m_?e6(BUW)Xm7ZkV4M'
        'z1i%*`qY^5k#1&g7Q0CtXI-+i?Ge5IUw&stS#>4**ZgWR%e&b(4?H&RHJd>+xoHka*1Oy$F<r9+yVKv=`g4zp&93|kq8cf)S|0!a'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
